# XS
requires 'YAML::XS';
requires 'JSON::XS';
requires 'HTTP::Parser::XS';
requires 'Linux::Inotify2';
requires 'Cookie::Baker::XS';

# servers
requires 'Server::Starter';
requires 'Monoceros';
requires 'Starlet';
requires 'Starman';

# framework and code
requires 'Kossy', 0.19;
requires 'DBD::mysql';
requires 'DBIx::Sunny';
requires 'Digest::SHA';
requires 'Data::MessagePack';
requires 'Compress::LZ4';
requires 'Cache::Memcached::Fast';
requires 'Redis::Fast';
requires 'List::MoreUtils';
requires 'Test::Fatal'; # for Time::Moment (TODO: p-r)
requires 'Time::Moment';

# init.pl
requires 'Parallel::Async';
requires 'Data::Section::Simple';
requires 'List::Util';

# app.psgi
requires 'Plack';
requires 'Plack::Middleware::Session::Simple';
