# XS
requires 'YAML::XS';
requires 'JSON::XS';
requires 'HTTP::Parser::XS';
requires 'Linux::Inotify2';

# servers
requires 'Server::Starter';
requires 'Monoceros';
requires 'Starlet';
requires 'Starman';

# framework and code
requires 'Kossy', 0.19;
requires 'DBD::mysql';
requires 'DBIx::Sunny';
requires 'Digest::SHA';
requires 'Data::MessagePack';
requires 'Compress::LZ4';
requires 'Cache::Memcached::Fast';

# app.psgi
requires 'Plack';
requires 'Plack::Middleware::Session::Simple';
